env:
  NODE_ENV: development
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_0: "docker-compose.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG_1: "docker-compose.buildkite.yml"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY: "dominics/monofo"

steps:
  - label: "build docker containers"
    plugins:
      - docker-compose#v3.3.0:
          build: [node, node-14]

  - wait

  - label: "test app"
    command: "yarn test"
    plugins:
      - docker-compose#v3.3.0:
          run: node

  - label: "test app on node-14"
    command: "yarn test"
    plugins:
      - docker-compose#v3.3.0:
          run: node-14

  - wait

  - label: "plan release"
    command: "yarn run release --dry-run"
    branches: main
    plugins:
      - docker-compose#v3.3.0:
          run: node

  - block: "unblock"

  - label: "release"
    command: "yarn run release"
    branches: main
    plugins:
      - docker-compose#v3.3.0:
          run: node
